// Mock data for the Sankofa Admin Dashboard enriched to mirror mobile app entities

import { BellRing, CalendarClock, ClipboardCheck, MessageSquareText, Search, Sparkles } from 'lucide-react';

import type { LucideIcon } from 'lucide-react';

type NotificationTemplateKey = 'depositSuccess' | 'payoutReminder' | 'savingsMilestone';

type PlatformConfiguration = {
  fees: {
    deposit: number;
    withdrawal: number;
    savingsBoost: number;
    payoutBufferDays: number;
    manualReviewThreshold: number;
  };
  notifications: {
    templates: Record<NotificationTemplateKey, { subject: string; body: string }>;
    catalogue: Record<
      NotificationTemplateKey,
      {
        title: string;
        description: string;
        subjectPlaceholder: string;
        bodyPlaceholder: string;
        previewTitle: string;
        icon: LucideIcon;
      }
    >;
  };
  localization: {
    supportedLanguages: string[];
    defaultLanguage: string;
  };
};

type PublicGroupJoinFlow = {
  expectation: string;
  steps: Array<{
    id: string;
    badge: string;
    title: string;
    description: string;
    helper: string;
    icon: LucideIcon;
  }>;
  highlights: string[];
};

export const platformConfiguration: PlatformConfiguration = {
  fees: {
    deposit: 2.5,
    withdrawal: 3.8,
    savingsBoost: 1.2,
    payoutBufferDays: 2,
    manualReviewThreshold: 1500,
  },
  notifications: {
    templates: {
      depositSuccess: {
        subject: 'Deposit confirmed: GH₵ {{amount}} received',
        body: 'Hi {{memberName}}, we have received your mobile money deposit of GH₵ {{amount}} into your Sankofa wallet. Funds clear instantly and the new balance is GH₵ {{balance}}.',
      },
      payoutReminder: {
        subject: 'Upcoming susu payout scheduled on {{cycleDate}}',
        body: 'Heads up {{memberName}}—your susu group payout is scheduled for {{cycleDate}}. Kindly ensure your MoMo wallet has the required float and review the payout destination before {{reviewBy}}.',
      },
      savingsMilestone: {
        subject: '🎉 You just crossed {{milestone}} of your savings goal',
        body: 'Amazing work {{memberName}}! You have contributed GH₵ {{amountContributed}} which is {{milestone}} of your {{goalName}} savings goal. Keep the momentum going with an optional boost this week.',
      },
    },
    catalogue: {
      depositSuccess: {
        title: 'Deposit confirmation',
        description: 'Notifies members and operators when deposits land successfully.',
        subjectPlaceholder: 'Deposit confirmed: GH₵ 2,400 received',
        bodyPlaceholder:
          'Hi Ama, we have received your mobile money deposit of GH₵ 2,400 into your Sankofa wallet. Funds clear instantly and the new balance is GH₵ 4,820.15.',
        previewTitle: 'Mobile & email preview',
        icon: BellRing,
      },
      payoutReminder: {
        title: 'Payout reminder',
        description: 'Shared before upcoming susu group disbursements.',
        subjectPlaceholder: 'Upcoming susu payout scheduled on 24 Jan',
        bodyPlaceholder:
          'Heads up Ama—your susu group payout is scheduled for 24 Jan. Kindly ensure your MoMo wallet has the required float and review the payout destination before 22 Jan.',
        previewTitle: 'Group operations preview',
        icon: CalendarClock,
      },
      savingsMilestone: {
        title: 'Savings milestone celebration',
        description: 'Encourages members who cross major savings percentages.',
        subjectPlaceholder: '🎉 You just crossed 75% of your savings goal',
        bodyPlaceholder:
          'Amazing work Ama! You have contributed GH₵ 3,000 which is 75% of your Back-to-School savings goal. Keep the momentum going with an optional boost this week.',
        previewTitle: 'Engagement preview',
        icon: MessageSquareText,
      },
    },
  },
  localization: {
    supportedLanguages: ['en', 'tw', 'ee'],
    defaultLanguage: 'en',
  },
};

export const mockUsers = [
  {
    id: 'user_001',
    name: 'Kwame Mensah',
    phone: '+233 24 123 4567',
    email: 'kwame.mensah@example.com',
    kycStatus: 'Approved',
    walletBalance: 2450.32,
    status: 'Active',
    joinedDate: '2023-11-02',
    avatar: 'KM',
    location: 'Accra, Ghana',
    lastActive: '2025-01-15 09:45',
    riskLevel: 'Low',
    walletDelta: 12.4,
    flagged: false,
  },
  {
    id: 'user_002',
    name: 'Ama Darko',
    phone: '+233 20 777 4410',
    email: 'ama.darko@example.com',
    kycStatus: 'Pending',
    walletBalance: 1840.75,
    status: 'Active',
    joinedDate: '2024-01-08',
    avatar: 'AD',
    location: 'Kumasi, Ghana',
    lastActive: '2025-01-15 09:10',
    riskLevel: 'Medium',
    walletDelta: 6.1,
    flagged: false,
  },
  {
    id: 'user_003',
    name: 'Kofi Asante',
    phone: '+233 55 218 9034',
    email: 'kofi.asante@example.com',
    kycStatus: 'Approved',
    walletBalance: 3680.4,
    status: 'Active',
    joinedDate: '2023-09-17',
    avatar: 'KA',
    location: 'Accra, Ghana',
    lastActive: '2025-01-15 08:55',
    riskLevel: 'Low',
    walletDelta: 10.8,
    flagged: false,
  },
  {
    id: 'user_004',
    name: 'Abena Osei',
    phone: '+233 27 110 4582',
    email: 'abena.osei@example.com',
    kycStatus: 'Approved',
    walletBalance: 1295.1,
    status: 'Active',
    joinedDate: '2024-02-21',
    avatar: 'AO',
    location: 'Takoradi, Ghana',
    lastActive: '2025-01-14 21:05',
    riskLevel: 'Low',
    walletDelta: 4.3,
    flagged: false,
  },
  {
    id: 'user_005',
    name: 'Yaw Boateng',
    phone: '+233 24 880 5521',
    email: 'yaw.boateng@example.com',
    kycStatus: 'Approved',
    walletBalance: 950,
    status: 'Suspended',
    joinedDate: '2023-12-12',
    avatar: 'YB',
    location: 'Accra, Ghana',
    lastActive: '2025-01-10 20:04',
    riskLevel: 'High',
    walletDelta: -18.5,
    flagged: true,
  },
  {
    id: 'user_006',
    name: 'Akua Frimpong',
    phone: '+233 23 998 1200',
    email: 'akua.frimpong@example.com',
    kycStatus: 'Pending',
    walletBalance: 420.55,
    status: 'Active',
    joinedDate: '2024-03-03',
    avatar: 'AF',
    location: 'Cape Coast, Ghana',
    lastActive: '2025-01-14 19:20',
    riskLevel: 'Medium',
    walletDelta: 2.7,
    flagged: false,
  },
  {
    id: 'user_007',
    name: 'Efua Adjei',
    phone: '+233 30 660 9033',
    email: 'efua.adjei@example.com',
    kycStatus: 'Approved',
    walletBalance: 2580.9,
    status: 'Active',
    joinedDate: '2023-10-26',
    avatar: 'EA',
    location: 'Accra, Ghana',
    lastActive: '2025-01-14 18:05',
    riskLevel: 'Low',
    walletDelta: 7.5,
    flagged: false,
  },
  {
    id: 'user_008',
    name: 'Adwoa Mensah',
    phone: '+233 50 214 7741',
    email: 'adwoa.mensah@example.com',
    kycStatus: 'Approved',
    walletBalance: 740.25,
    status: 'Active',
    joinedDate: '2024-04-04',
    avatar: 'AM',
    location: 'Tema, Ghana',
    lastActive: '2025-01-15 07:40',
    riskLevel: 'Low',
    walletDelta: 5.2,
    flagged: false,
  },
  {
    id: 'user_009',
    name: 'Kwesi Owusu',
    phone: '+233 55 502 1109',
    email: 'kwesi.owusu@example.com',
    kycStatus: 'Pending',
    walletBalance: 1140,
    status: 'Active',
    joinedDate: '2023-08-19',
    avatar: 'KO',
    location: 'Koforidua, Ghana',
    lastActive: '2025-01-14 20:35',
    riskLevel: 'Medium',
    walletDelta: 3.4,
    flagged: false,
  },
  {
    id: 'user_010',
    name: 'Nana Agyeman',
    phone: '+233 24 101 3388',
    email: 'nana.agyeman@example.com',
    kycStatus: 'Approved',
    walletBalance: 3015.8,
    status: 'Active',
    joinedDate: '2023-09-05',
    avatar: 'NA',
    location: 'Accra, Ghana',
    lastActive: '2025-01-15 06:55',
    riskLevel: 'Low',
    walletDelta: 9.1,
    flagged: false,
  },
  {
    id: 'user_011',
    name: 'Kojo Addai',
    phone: '+233 57 442 1100',
    email: 'kojo.addai@example.com',
    kycStatus: 'Approved',
    walletBalance: 1880.45,
    status: 'Inactive',
    joinedDate: '2022-12-15',
    avatar: 'KA',
    location: 'Sunyani, Ghana',
    lastActive: '2025-01-12 16:00',
    riskLevel: 'Medium',
    walletDelta: -2.5,
    flagged: false,
  },
  {
    id: 'user_012',
    name: 'Yaa Appiah',
    phone: '+233 26 440 9981',
    email: 'yaa.appiah@example.com',
    kycStatus: 'Rejected',
    walletBalance: 0,
    status: 'Inactive',
    joinedDate: '2024-03-27',
    avatar: 'YA',
    location: 'Tamale, Ghana',
    lastActive: '2024-03-28 13:10',
    riskLevel: 'High',
    walletDelta: 0,
    flagged: true,
  },
  {
    id: 'user_013',
    name: 'Kwabena Ofori',
    phone: '+233 55 778 1204',
    email: 'kwabena.ofori@example.com',
    kycStatus: 'Approved',
    walletBalance: 1655.2,
    status: 'Active',
    joinedDate: '2023-07-11',
    avatar: 'KO',
    location: 'Cape Coast, Ghana',
    lastActive: '2025-01-14 17:20',
    riskLevel: 'Low',
    walletDelta: 4.9,
    flagged: false,
  },
  {
    id: 'user_014',
    name: 'Esi Boateng',
    phone: '+233 24 908 2245',
    email: 'esi.boateng@example.com',
    kycStatus: 'Approved',
    walletBalance: 2120,
    status: 'Active',
    joinedDate: '2023-11-19',
    avatar: 'EB',
    location: 'Accra, Ghana',
    lastActive: '2025-01-14 12:50',
    riskLevel: 'Low',
    walletDelta: 6.4,
    flagged: false,
  },
  {
    id: 'user_015',
    name: 'Rita Amankwah',
    phone: '+233 20 667 3351',
    email: 'rita.amankwah@example.com',
    kycStatus: 'Pending',
    walletBalance: 980.75,
    status: 'Active',
    joinedDate: '2024-01-28',
    avatar: 'RA',
    location: 'Kumasi, Ghana',
    lastActive: '2025-01-14 09:30',
    riskLevel: 'Medium',
    walletDelta: 3.8,
    flagged: false,
  },
  {
    id: 'user_016',
    name: 'Kojo Nyarko',
    phone: '+233 27 311 7700',
    email: 'kojo.nyarko@example.com',
    kycStatus: 'Approved',
    walletBalance: 1425.6,
    status: 'Active',
    joinedDate: '2022-10-22',
    avatar: 'KN',
    location: 'Ho, Ghana',
    lastActive: '2025-01-13 22:05',
    riskLevel: 'Low',
    walletDelta: 2.1,
    flagged: false,
  },
];

export const mockSusuGroups = [
  {
    id: 'group_001',
    name: 'Unity Savers Group',
    members: 6,
    contributionAmount: 200,
    frequency: 'Weekly',
    cycleProgress: 62,
    totalPooled: 7440,
    nextPayoutDate: '2025-02-02',
    status: 'Active',
    visibility: 'Private',
    cycleStage: 'Contributions',
    inviteCompletion: 83,
    inviteStats: { total: 12, accepted: 10, pending: 2, declined: 0 },
    remindersDue: 1,
    remindersSent: 3,
    lastReminderAt: '2025-01-14T09:15:00Z',
    nextPayout: {
      member: 'Ama Darko',
      amount: 1000,
      window: 'Cycle 6',
      scheduledAt: '2025-02-02',
    },
    contributionWindow: 'Sundays 06:00-18:00 GMT',
    riskFlags: ['Pending KYC follow-up for 2 invites'],
    membersList: [
      {
        name: 'Kwame Mensah',
        currentRotation: 'Paid',
        amount: 1000,
        lastContribution: '2025-01-12',
        status: 'On Track',
        payoutPosition: 'Cycle 5',
        role: 'Lead Organizer',
      },
      {
        name: 'Ama Darko',
        currentRotation: 'Next',
        amount: 1000,
        lastContribution: '2025-01-12',
        status: 'Upcoming Payout',
        payoutPosition: 'Cycle 6',
        role: 'Treasurer',
      },
      {
        name: 'Kofi Asante',
        currentRotation: 'Pending',
        amount: 1000,
        lastContribution: '2025-01-11',
        status: 'On Track',
        payoutPosition: 'Cycle 7',
        role: 'Member',
      },
      {
        name: 'Yaw Boateng',
        currentRotation: 'Pending',
        amount: 1000,
        lastContribution: '2025-01-10',
        status: 'Late Contribution',
        payoutPosition: 'Cycle 8',
        role: 'Member',
      },
      {
        name: 'Efua Adjei',
        currentRotation: 'Pending',
        amount: 1000,
        lastContribution: '2025-01-09',
        status: 'On Track',
        payoutPosition: 'Cycle 9',
        role: 'Member',
      },
      {
        name: 'Akua Frimpong',
        currentRotation: 'Pending',
        amount: 1000,
        lastContribution: '2025-01-08',
        status: 'Onboarding',
        payoutPosition: 'Cycle 10',
        role: 'Member',
      },
    ],
    invites: [
      {
        name: 'Naana Eshun',
        phone: '+233 24 921 1100',
        status: 'Pending',
        kycCompleted: false,
        sentAt: '2025-01-05T10:00:00Z',
        lastRemindedAt: '2025-01-14T09:15:00Z',
        channel: 'SMS',
      },
      {
        name: 'Felix Aidoo',
        phone: '+233 20 555 9988',
        status: 'Pending',
        kycCompleted: true,
        sentAt: '2025-01-07T12:30:00Z',
        lastRemindedAt: '2025-01-14T09:15:00Z',
        channel: 'Email',
      },
      {
        name: 'Gifty Lawson',
        phone: '+233 55 678 2210',
        status: 'Accepted',
        kycCompleted: true,
        sentAt: '2024-12-15T08:00:00Z',
        respondedAt: '2024-12-16T09:00:00Z',
        channel: 'SMS',
      },
    ],
    payoutTimeline: [
      {
        label: 'Cycle 4',
        member: 'Yaw Boateng',
        scheduledAt: '2025-01-26',
        status: 'Scheduled',
      },
      {
        label: 'Cycle 3',
        member: 'Kofi Asante',
        scheduledAt: '2025-01-19',
        status: 'Paid',
      },
      {
        label: 'Cycle 2',
        member: 'Kwame Mensah',
        scheduledAt: '2025-01-12',
        status: 'Paid',
      },
    ],
    outstandingReminders: [
      {
        title: 'Collect ID documents from Naana',
        dueAt: '2025-01-20',
        owner: 'Group Success Team',
      },
    ],
  },
  {
    id: 'group_002',
    name: 'Women Empowerment Circle',
    members: 5,
    contributionAmount: 150,
    frequency: 'Bi-weekly',
    cycleProgress: 48,
    totalPooled: 3600,
    nextPayoutDate: '2025-02-10',
    status: 'Active',
    visibility: 'Private',
    cycleStage: 'Payout',
    inviteCompletion: 68,
    inviteStats: { total: 9, accepted: 6, pending: 2, declined: 1 },
    remindersDue: 2,
    remindersSent: 1,
    lastReminderAt: '2025-01-13T16:20:00Z',
    nextPayout: {
      member: 'Akua Frimpong',
      amount: 750,
      window: 'Wave 4',
      scheduledAt: '2025-02-10',
    },
    contributionWindow: 'Fridays 07:00-20:00 GMT',
    riskFlags: ['One invite declined participation'],
    membersList: [
      {
        name: 'Akua Frimpong',
        currentRotation: 'Next',
        amount: 750,
        lastContribution: '2025-01-11',
        status: 'Awaiting Payout',
        payoutPosition: 'Wave 4',
        role: 'Treasurer',
      },
      {
        name: 'Efua Adjei',
        currentRotation: 'Paid',
        amount: 750,
        lastContribution: '2025-01-11',
        status: 'Paid Out',
        payoutPosition: 'Wave 3',
        role: 'Secretary',
      },
      {
        name: 'Adwoa Mensah',
        currentRotation: 'Pending',
        amount: 750,
        lastContribution: '2025-01-10',
        status: 'On Track',
        payoutPosition: 'Wave 5',
        role: 'Member',
      },
      {
        name: 'Esi Boateng',
        currentRotation: 'Pending',
        amount: 750,
        lastContribution: '2025-01-09',
        status: 'On Track',
        payoutPosition: 'Wave 6',
        role: 'Member',
      },
      {
        name: 'Rita Amankwah',
        currentRotation: 'Pending',
        amount: 750,
        lastContribution: '2025-01-09',
        status: 'Grace Period',
        payoutPosition: 'Wave 7',
        role: 'Member',
      },
    ],
    invites: [
      {
        name: 'Leticia Oppong',
        phone: '+233 55 211 6789',
        status: 'Pending',
        kycCompleted: false,
        sentAt: '2025-01-08T13:00:00Z',
        lastRemindedAt: '2025-01-13T16:20:00Z',
        channel: 'WhatsApp',
      },
      {
        name: 'Cynthia Mensima',
        phone: '+233 24 802 3355',
        status: 'Declined',
        kycCompleted: false,
        sentAt: '2025-01-04T09:45:00Z',
        respondedAt: '2025-01-05T10:10:00Z',
        channel: 'SMS',
      },
      {
        name: 'Akosua Boateng',
        phone: '+233 20 678 4455',
        status: 'Accepted',
        kycCompleted: true,
        sentAt: '2024-12-10T15:00:00Z',
        respondedAt: '2024-12-12T11:00:00Z',
        channel: 'Email',
      },
    ],
    payoutTimeline: [
      {
        label: 'Wave 3',
        member: 'Efua Adjei',
        scheduledAt: '2025-01-14',
        status: 'Paid',
      },
      {
        label: 'Wave 2',
        member: 'Adwoa Mensah',
        scheduledAt: '2025-01-01',
        status: 'Paid',
      },
      {
        label: 'Wave 1',
        member: 'Esi Boateng',
        scheduledAt: '2024-12-18',
        status: 'Paid',
      },
    ],
    outstandingReminders: [
      {
        title: 'Follow up with Leticia on KYC upload',
        dueAt: '2025-01-18',
        owner: 'Women Empowerment Ops',
      },
      {
        title: 'Confirm payout float availability',
        dueAt: '2025-01-20',
        owner: 'Finance Desk',
      },
    ],
  },
  {
    id: 'group_003',
    name: 'Traders Alliance',
    members: 6,
    contributionAmount: 300,
    frequency: 'Monthly',
    cycleProgress: 54,
    totalPooled: 9720,
    nextPayoutDate: '2025-02-18',
    status: 'Active',
    visibility: 'Private',
    cycleStage: 'Contributions',
    inviteCompletion: 91,
    inviteStats: { total: 14, accepted: 13, pending: 1, declined: 0 },
    remindersDue: 0,
    remindersSent: 4,
    lastReminderAt: '2025-01-10T08:45:00Z',
    nextPayout: {
      member: 'Nana Agyeman',
      amount: 1800,
      window: 'Month 6',
      scheduledAt: '2025-02-18',
    },
    contributionWindow: '15th of every month',
    riskFlags: ['High float volume—monitor liquidity'],
    membersList: [
      {
        name: 'Kwesi Owusu',
        currentRotation: 'Paid',
        amount: 1800,
        lastContribution: '2025-01-15',
        status: 'Paid Out',
        payoutPosition: 'Month 4',
        role: 'Chairperson',
      },
      {
        name: 'Nana Agyeman',
        currentRotation: 'Next',
        amount: 1800,
        lastContribution: '2025-01-15',
        status: 'On Track',
        payoutPosition: 'Month 6',
        role: 'Treasurer',
      },
      {
        name: 'Kojo Addai',
        currentRotation: 'Pending',
        amount: 1800,
        lastContribution: '2025-01-14',
        status: 'On Track',
        payoutPosition: 'Month 7',
        role: 'Member',
      },
      {
        name: 'Kojo Nyarko',
        currentRotation: 'Pending',
        amount: 1800,
        lastContribution: '2025-01-14',
        status: 'On Track',
        payoutPosition: 'Month 8',
        role: 'Member',
      },
      {
        name: 'Agnes Quaye',
        currentRotation: 'Pending',
        amount: 1800,
        lastContribution: '2025-01-13',
        status: 'On Track',
        payoutPosition: 'Month 9',
        role: 'Member',
      },
      {
        name: 'Felix Aidoo',
        currentRotation: 'Pending',
        amount: 1800,
        lastContribution: '2025-01-13',
        status: 'On Track',
        payoutPosition: 'Month 10',
        role: 'Member',
      },
    ],
    invites: [
      {
        name: 'Akosua Nyame',
        phone: '+233 55 332 1199',
        status: 'Accepted',
        kycCompleted: true,
        sentAt: '2024-12-01T09:00:00Z',
        respondedAt: '2024-12-02T11:30:00Z',
        channel: 'SMS',
      },
      {
        name: 'Yaw Kyei',
        phone: '+233 24 908 7766',
        status: 'Pending',
        kycCompleted: true,
        sentAt: '2025-01-12T10:15:00Z',
        lastRemindedAt: '2025-01-10T08:45:00Z',
        channel: 'Email',
      },
    ],
    payoutTimeline: [
      {
        label: 'Month 5',
        member: 'Kojo Addai',
        scheduledAt: '2025-01-18',
        status: 'Scheduled',
      },
      {
        label: 'Month 4',
        member: 'Kwesi Owusu',
        scheduledAt: '2024-12-18',
        status: 'Paid',
      },
      {
        label: 'Month 3',
        member: 'Nana Agyeman',
        scheduledAt: '2024-11-18',
        status: 'Paid',
      },
    ],
    outstandingReminders: [
      {
        title: 'Monitor liquidity buffer before next payout',
        dueAt: '2025-02-12',
        owner: 'Finance Desk',
      },
    ],
  },
  {
    id: 'group_public_001',
    name: 'Accra Market Vendors',
    members: 5,
    contributionAmount: 180,
    frequency: 'Weekly',
    cycleProgress: 28,
    totalPooled: 3150,
    nextPayoutDate: '2025-01-28',
    status: 'Active',
    visibility: 'Public',
    cycleStage: 'Onboarding',
    inviteCompletion: 52,
    inviteStats: { total: 11, accepted: 6, pending: 4, declined: 1 },
    remindersDue: 3,
    remindersSent: 1,
    lastReminderAt: '2025-01-12T07:30:00Z',
    nextPayout: {
      member: 'Kojo Nyarko',
      amount: 900,
      window: 'Cycle 2',
      scheduledAt: '2025-01-28',
    },
    contributionWindow: 'Mondays 05:00-17:00 GMT',
    riskFlags: ['Invite completion below 60%'],
    membersList: [
      {
        name: 'Esi Boateng',
        currentRotation: 'Paid',
        amount: 900,
        lastContribution: '2025-01-08',
        status: 'Paid Out',
        payoutPosition: 'Cycle 1',
        role: 'Market Lead',
      },
      {
        name: 'Rita Amankwah',
        currentRotation: 'Pending',
        amount: 900,
        lastContribution: '2025-01-07',
        status: 'Grace Period',
        payoutPosition: 'Cycle 3',
        role: 'Member',
      },
      {
        name: 'Kojo Nyarko',
        currentRotation: 'Next',
        amount: 900,
        lastContribution: '2025-01-07',
        status: 'Upcoming Payout',
        payoutPosition: 'Cycle 2',
        role: 'Member',
      },
      {
        name: 'Sarah Ackah',
        currentRotation: 'Pending',
        amount: 900,
        lastContribution: '2025-01-06',
        status: 'Onboarding',
        payoutPosition: 'Cycle 4',
        role: 'Member',
      },
      {
        name: 'Kwame Anane',
        currentRotation: 'Pending',
        amount: 900,
        lastContribution: '2025-01-06',
        status: 'Onboarding',
        payoutPosition: 'Cycle 5',
        role: 'Member',
      },
    ],
    invites: [
      {
        name: 'Patience Owusu',
        phone: '+233 20 123 8899',
        status: 'Pending',
        kycCompleted: false,
        sentAt: '2025-01-06T06:00:00Z',
        lastRemindedAt: '2025-01-12T07:30:00Z',
        channel: 'SMS',
      },
      {
        name: 'Selorm Akorfa',
        phone: '+233 55 100 5522',
        status: 'Pending',
        kycCompleted: false,
        sentAt: '2025-01-06T06:00:00Z',
        lastRemindedAt: '2025-01-12T07:30:00Z',
        channel: 'WhatsApp',
      },
      {
        name: 'Yaw Manu',
        phone: '+233 24 788 2234',
        status: 'Declined',
        kycCompleted: false,
        sentAt: '2025-01-05T10:00:00Z',
        respondedAt: '2025-01-06T12:00:00Z',
        channel: 'SMS',
      },
    ],
    payoutTimeline: [
      {
        label: 'Cycle 2',
        member: 'Kojo Nyarko',
        scheduledAt: '2025-01-28',
        status: 'Scheduled',
      },
      {
        label: 'Cycle 1',
        member: 'Esi Boateng',
        scheduledAt: '2025-01-14',
        status: 'Paid',
      },
    ],
    outstandingReminders: [
      {
        title: 'Schedule onboarding webinar for pending invites',
        dueAt: '2025-01-19',
        owner: 'Community Team',
      },
      {
        title: 'Review declined invite feedback',
        dueAt: '2025-01-17',
        owner: 'Group Success Team',
      },
    ],
  },
  {
    id: 'group_public_002',
    name: 'Ashesi Alumni Builders',
    members: 4,
    contributionAmount: 400,
    frequency: 'Bi-weekly',
    cycleProgress: 36,
    totalPooled: 3840,
    nextPayoutDate: '2025-02-05',
    status: 'Active',
    visibility: 'Public',
    cycleStage: 'Contributions',
    inviteCompletion: 87,
    inviteStats: { total: 8, accepted: 7, pending: 1, declined: 0 },
    remindersDue: 1,
    remindersSent: 2,
    lastReminderAt: '2025-01-11T18:10:00Z',
    nextPayout: {
      member: 'Kojo Nyarko',
      amount: 1600,
      window: 'Sprint 4',
      scheduledAt: '2025-02-05',
    },
    contributionWindow: 'Wednesdays 18:00 GMT (virtual)',
    riskFlags: ['Monitor remote member engagement'],
    membersList: [
      {
        name: 'Kwabena Ofori',
        currentRotation: 'Pending',
        amount: 1600,
        lastContribution: '2025-01-10',
        status: 'On Track',
        payoutPosition: 'Sprint 5',
        role: 'Convener',
      },
      {
        name: 'Kojo Nyarko',
        currentRotation: 'Next',
        amount: 1600,
        lastContribution: '2025-01-10',
        status: 'Upcoming Payout',
        payoutPosition: 'Sprint 4',
        role: 'Treasurer',
      },
      {
        name: 'Naana Eshun',
        currentRotation: 'Pending',
        amount: 1600,
        lastContribution: '2025-01-09',
        status: 'On Track',
        payoutPosition: 'Sprint 6',
        role: 'Member',
      },
      {
        name: 'Felix Aidoo',
        currentRotation: 'Pending',
        amount: 1600,
        lastContribution: '2025-01-09',
        status: 'On Track',
        payoutPosition: 'Sprint 7',
        role: 'Member',
      },
    ],
    invites: [
      {
        name: 'Yaw Bediako',
        phone: '+233 20 300 4411',
        status: 'Accepted',
        kycCompleted: true,
        sentAt: '2024-12-18T10:00:00Z',
        respondedAt: '2024-12-18T16:00:00Z',
        channel: 'Email',
      },
      {
        name: 'Dzifa Sewornu',
        phone: '+233 24 222 7711',
        status: 'Pending',
        kycCompleted: false,
        sentAt: '2025-01-09T09:00:00Z',
        lastRemindedAt: '2025-01-11T18:10:00Z',
        channel: 'WhatsApp',
      },
    ],
    payoutTimeline: [
      {
        label: 'Sprint 3',
        member: 'Naana Eshun',
        scheduledAt: '2025-01-22',
        status: 'Scheduled',
      },
      {
        label: 'Sprint 2',
        member: 'Kwabena Ofori',
        scheduledAt: '2025-01-08',
        status: 'Paid',
      },
      {
        label: 'Sprint 1',
        member: 'Felix Aidoo',
        scheduledAt: '2024-12-25',
        status: 'Paid',
      },
    ],
    outstandingReminders: [
      {
        title: 'Send project update template before Sprint 4',
        dueAt: '2025-01-19',
        owner: 'Program Manager',
      },
    ],
  },
  {
    id: 'group_public_003',
    name: 'Cape Coast Teachers Fund',
    members: 6,
    contributionAmount: 220,
    frequency: 'Monthly',
    cycleProgress: 88,
    totalPooled: 11616,
    nextPayoutDate: '2025-01-25',
    status: 'Completing',
    visibility: 'Public',
    cycleStage: 'Completed',
    inviteCompletion: 95,
    inviteStats: { total: 15, accepted: 14, pending: 1, declined: 0 },
    remindersDue: 0,
    remindersSent: 5,
    lastReminderAt: '2025-01-05T14:00:00Z',
    nextPayout: {
      member: 'Felix Aidoo',
      amount: 1320,
      window: 'Closing Cycle',
      scheduledAt: '2025-01-25',
    },
    contributionWindow: 'Last Friday of the month',
    riskFlags: ['Prepare graduation comms'],
    membersList: [
      {
        name: 'Agnes Quaye',
        currentRotation: 'Paid',
        amount: 1320,
        lastContribution: '2024-12-28',
        status: 'Complete',
        payoutPosition: 'Cycle 4',
        role: 'Chairperson',
      },
      {
        name: 'Naana Eshun',
        currentRotation: 'Paid',
        amount: 1320,
        lastContribution: '2024-12-28',
        status: 'Complete',
        payoutPosition: 'Cycle 5',
        role: 'Secretary',
      },
      {
        name: 'Felix Aidoo',
        currentRotation: 'Next',
        amount: 1320,
        lastContribution: '2024-12-28',
        status: 'Upcoming Payout',
        payoutPosition: 'Cycle 6',
        role: 'Treasurer',
      },
      {
        name: 'Kojo Nyarko',
        currentRotation: 'Pending',
        amount: 1320,
        lastContribution: '2024-12-27',
        status: 'Complete',
        payoutPosition: 'Cycle 7',
        role: 'Member',
      },
      {
        name: 'Esi Boateng',
        currentRotation: 'Pending',
        amount: 1320,
        lastContribution: '2024-12-27',
        status: 'Complete',
        payoutPosition: 'Cycle 8',
        role: 'Member',
      },
      {
        name: 'Rita Amankwah',
        currentRotation: 'Pending',
        amount: 1320,
        lastContribution: '2024-12-26',
        status: 'Complete',
        payoutPosition: 'Cycle 9',
        role: 'Member',
      },
    ],
    invites: [
      {
        name: 'Mawuli Korkor',
        phone: '+233 50 889 1177',
        status: 'Accepted',
        kycCompleted: true,
        sentAt: '2024-11-10T14:30:00Z',
        respondedAt: '2024-11-10T18:45:00Z',
        channel: 'Email',
      },
      {
        name: 'Vida Addy',
        phone: '+233 24 567 8899',
        status: 'Pending',
        kycCompleted: true,
        sentAt: '2025-01-02T09:00:00Z',
        lastRemindedAt: '2025-01-05T14:00:00Z',
        channel: 'SMS',
      },
    ],
    payoutTimeline: [
      {
        label: 'Cycle 8',
        member: 'Esi Boateng',
        scheduledAt: '2024-12-30',
        status: 'Paid',
      },
      {
        label: 'Cycle 7',
        member: 'Kojo Nyarko',
        scheduledAt: '2024-12-15',
        status: 'Paid',
      },
      {
        label: 'Cycle 6',
        member: 'Felix Aidoo',
        scheduledAt: '2024-12-01',
        status: 'Paid',
      },
    ],
    outstandingReminders: [
      {
        title: 'Plan graduation ceremony agenda',
        dueAt: '2025-01-22',
        owner: 'Community Team',
      },
      {
        title: 'Archive final payout receipts',
        dueAt: '2025-01-30',
        owner: 'Finance Desk',
      },
    ],
  },
];

export const mockTransactions = [
  {
    id: 'TXN-24022',
    date: '2025-01-15 10:30',
    timestamp: '2025-01-15T10:30:00Z',
    user: 'Unity Savers Group',
    userId: 'group_001',
    type: 'Payout',
    amount: 1000.0,
    status: 'Pending',
    reference: 'PAY-1182',
    channel: 'Group Wallet',
    description: 'Cycle 5 payout awaiting approval',
    fee: 0,
  },
  {
    id: 'TXN-24021',
    date: '2025-01-15 09:45',
    timestamp: '2025-01-15T09:45:00Z',
    user: 'Kwame Mensah',
    userId: 'user_001',
    type: 'Deposit',
    amount: 500.5,
    status: 'Success',
    reference: 'DEP-882154',
    channel: 'MTN MoMo',
    description: 'Wallet top-up via MTN',
    fee: 3.5,
  },
  {
    id: 'TXN-24020',
    date: '2025-01-15 09:10',
    timestamp: '2025-01-15T09:10:00Z',
    user: 'Ama Darko',
    userId: 'user_002',
    type: 'Deposit',
    amount: 320.0,
    status: 'Success',
    reference: 'DEP-771203',
    channel: 'Vodafone Cash',
    description: 'Wallet funding for Unity Savers',
    fee: 2.4,
  },
  {
    id: 'TXN-24019',
    date: '2025-01-14 18:22',
    timestamp: '2025-01-14T18:22:00Z',
    user: 'Kofi Asante',
    userId: 'user_003',
    type: 'Deposit',
    amount: 680.0,
    status: 'Success',
    reference: 'DEP-661204',
    channel: 'Bank Transfer',
    description: 'Float deposit for payouts',
    fee: 4.1,
  },
  {
    id: 'TXN-24018',
    date: '2025-01-14 17:05',
    timestamp: '2025-01-14T17:05:00Z',
    user: 'Abena Osei',
    userId: 'user_004',
    type: 'Deposit',
    amount: 250.0,
    status: 'Success',
    reference: 'DEP-551204',
    channel: 'MTN MoMo',
    description: 'Weekly contribution funding',
    fee: 1.8,
  },
  {
    id: 'TXN-24017',
    date: '2025-01-14 16:40',
    timestamp: '2025-01-14T16:40:00Z',
    user: 'Yaw Boateng',
    userId: 'user_005',
    type: 'Deposit',
    amount: 180.0,
    status: 'Failed',
    reference: 'DEP-441205',
    channel: 'AirtelTigo Money',
    description: 'Deposit declined - KYC hold',
    fee: 0,
  },
  {
    id: 'TXN-24016',
    date: '2025-01-14 15:58',
    timestamp: '2025-01-14T15:58:00Z',
    user: 'Akua Frimpong',
    userId: 'user_006',
    type: 'Deposit',
    amount: 210.0,
    status: 'Pending',
    reference: 'DEP-331205',
    channel: 'MTN MoMo',
    description: 'Awaiting mobile confirmation',
    fee: 0,
  },
  {
    id: 'TXN-24015',
    date: '2025-01-14 12:26',
    timestamp: '2025-01-14T12:26:00Z',
    user: 'Efua Adjei',
    userId: 'user_007',
    type: 'Deposit',
    amount: 720.0,
    status: 'Success',
    reference: 'DEP-221205',
    channel: 'Bank Transfer',
    description: 'Business capital injection',
    fee: 4.75,
  },
  {
    id: 'TXN-24014',
    date: '2025-01-14 11:42',
    timestamp: '2025-01-14T11:42:00Z',
    user: 'Adwoa Mensah',
    userId: 'user_008',
    type: 'Deposit',
    amount: 150.0,
    status: 'Success',
    reference: 'DEP-221187',
    channel: 'MTN MoMo',
    description: 'Wallet boost before cycle',
    fee: 1.2,
  },
  {
    id: 'TXN-24013',
    date: '2025-01-13 19:33',
    timestamp: '2025-01-13T19:33:00Z',
    user: 'Kwesi Owusu',
    userId: 'user_009',
    type: 'Deposit',
    amount: 540.0,
    status: 'Success',
    reference: 'DEP-118530',
    channel: 'Bank Transfer',
    description: 'Traders Alliance float top-up',
    fee: 3.6,
  },
  {
    id: 'TXN-24012',
    date: '2025-01-13 09:18',
    timestamp: '2025-01-13T09:18:00Z',
    user: 'Nana Agyeman',
    userId: 'user_010',
    type: 'Deposit',
    amount: 810.0,
    status: 'Success',
    reference: 'DEP-771110',
    channel: 'MTN MoMo',
    description: 'Advance funding for payouts',
    fee: 5.2,
  },
  {
    id: 'TXN-24011',
    date: '2025-01-13 08:47',
    timestamp: '2025-01-13T08:47:00Z',
    user: 'Kwame Mensah',
    userId: 'user_001',
    type: 'Contribution',
    amount: 200.0,
    status: 'Success',
    reference: 'CIRC-8821',
    channel: 'Wallet Transfer',
    description: 'Unity Savers weekly contribution',
  },
  {
    id: 'TXN-24010',
    date: '2025-01-12 19:55',
    timestamp: '2025-01-12T19:55:00Z',
    user: 'Akua Frimpong',
    userId: 'user_006',
    type: 'Contribution',
    amount: 150.0,
    status: 'Pending',
    reference: 'CIRC-7710',
    channel: 'Wallet Transfer',
    description: 'Women Empowerment cycle 2',
  },
  {
    id: 'TXN-24009',
    date: '2025-01-12 18:40',
    timestamp: '2025-01-12T18:40:00Z',
    user: 'Efua Adjei',
    userId: 'user_007',
    type: 'Contribution',
    amount: 200.0,
    status: 'Success',
    reference: 'CIRC-6609',
    channel: 'Wallet Transfer',
    description: 'Women Empowerment cycle 2',
  },
  {
    id: 'TXN-24008',
    date: '2025-01-12 17:32',
    timestamp: '2025-01-12T17:32:00Z',
    user: 'Kwesi Owusu',
    userId: 'user_009',
    type: 'Contribution',
    amount: 300.0,
    status: 'Success',
    reference: 'CIRC-5508',
    channel: 'Wallet Transfer',
    description: 'Traders Alliance cycle 4',
  },
  {
    id: 'TXN-24007',
    date: '2025-01-11 16:14',
    timestamp: '2025-01-11T16:14:00Z',
    user: 'Adwoa Mensah',
    userId: 'user_008',
    type: 'Contribution',
    amount: 180.0,
    status: 'Success',
    reference: 'CIRC-4407',
    channel: 'Wallet Transfer',
    description: 'Accra Market Vendors cycle 1',
  },
  {
    id: 'TXN-24006',
    date: '2025-01-11 14:09',
    timestamp: '2025-01-11T14:09:00Z',
    user: 'Nana Agyeman',
    userId: 'user_010',
    type: 'Contribution',
    amount: 220.0,
    status: 'Success',
    reference: 'CIRC-3306',
    channel: 'Wallet Transfer',
    description: 'Traders Alliance cycle 4',
  },
  {
    id: 'TXN-24005',
    date: '2025-01-11 10:48',
    timestamp: '2025-01-11T10:48:00Z',
    user: 'Kwame Mensah',
    userId: 'user_001',
    type: 'Withdrawal',
    amount: 400.0,
    status: 'Success',
    reference: 'WDR-2205',
    channel: 'GTBank',
    description: 'Payout to business account',
    fee: 2.8,
  },
  {
    id: 'TXN-24004',
    date: '2025-01-10 21:20',
    timestamp: '2025-01-10T21:20:00Z',
    user: 'Ama Darko',
    userId: 'user_002',
    type: 'Withdrawal',
    amount: 250.0,
    status: 'Pending',
    reference: 'WDR-1104',
    channel: 'MTN MoMo',
    description: 'Cash out for vendor payments',
    fee: 0,
  },
  {
    id: 'TXN-24003',
    date: '2025-01-10 20:04',
    timestamp: '2025-01-10T20:04:00Z',
    user: 'Yaw Boateng',
    userId: 'user_005',
    type: 'Withdrawal',
    amount: 500.0,
    status: 'Failed',
    reference: 'WDR-0003',
    channel: 'Bank Transfer',
    description: 'Withdrawal rejected - compliance',
    fee: 0,
  },
  {
    id: 'TXN-24002',
    date: '2025-01-10 18:42',
    timestamp: '2025-01-10T18:42:00Z',
    user: 'Kofi Asante',
    userId: 'user_003',
    type: 'Payout',
    amount: 1000.0,
    status: 'Success',
    reference: 'PAY-1174',
    channel: 'Group Wallet',
    description: 'Unity Savers cycle payout',
    fee: 0,
  },
  {
    id: 'TXN-24001',
    date: '2025-01-10 17:33',
    timestamp: '2025-01-10T17:33:00Z',
    user: 'Kwabena Ofori',
    userId: 'user_013',
    type: 'Savings',
    amount: 175.0,
    status: 'Success',
    reference: 'SAVE-5521',
    channel: 'Wallet Transfer',
    description: 'Education fund auto-save',
  },
];

export const mockSavingsGoals = [
  {
    id: 'goal_001',
    userId: 'user_001',
    title: 'Expand Shopfront',
    category: 'Business Growth',
    targetAmount: 6000,
    currentAmount: 3200,
    status: 'Active',
    nextContributionDate: '2025-01-20',
    lastContributionDate: '2025-01-13',
    deadline: '2025-06-01',
  },
  {
    id: 'goal_002',
    userId: 'user_001',
    title: 'Emergency Reserve',
    category: 'Safety Net',
    targetAmount: 2000,
    currentAmount: 2000,
    status: 'Completed',
    nextContributionDate: null,
    lastContributionDate: '2025-01-05',
    deadline: '2025-01-05',
  },
  {
    id: 'goal_003',
    userId: 'user_002',
    title: 'Vendor Inventory Boost',
    category: 'Working Capital',
    targetAmount: 3500,
    currentAmount: 1450,
    status: 'Active',
    nextContributionDate: '2025-01-18',
    lastContributionDate: '2025-01-12',
    deadline: '2025-07-30',
  },
  {
    id: 'goal_004',
    userId: 'user_003',
    title: 'Delivery Van Down Payment',
    category: 'Logistics',
    targetAmount: 10000,
    currentAmount: 4800,
    status: 'Active',
    nextContributionDate: '2025-01-22',
    lastContributionDate: '2025-01-14',
    deadline: '2025-09-15',
  },
  {
    id: 'goal_005',
    userId: 'user_004',
    title: 'Salon Expansion',
    category: 'Business Growth',
    targetAmount: 2500,
    currentAmount: 1250,
    status: 'Active',
    nextContributionDate: '2025-01-19',
    lastContributionDate: '2025-01-11',
    deadline: '2025-05-01',
  },
  {
    id: 'goal_006',
    userId: 'user_006',
    title: 'Junior College Fund',
    category: 'Education',
    targetAmount: 4000,
    currentAmount: 1200,
    status: 'Dormant',
    nextContributionDate: null,
    lastContributionDate: '2024-11-30',
    deadline: '2025-10-30',
  },
  {
    id: 'goal_007',
    userId: 'user_007',
    title: 'Wedding Celebration',
    category: 'Family',
    targetAmount: 8000,
    currentAmount: 5200,
    status: 'Active',
    nextContributionDate: '2025-01-21',
    lastContributionDate: '2025-01-13',
    deadline: '2025-08-10',
  },
  {
    id: 'goal_008',
    userId: 'user_008',
    title: 'Market Stall Upgrade',
    category: 'Business Growth',
    targetAmount: 3000,
    currentAmount: 1680,
    status: 'Active',
    nextContributionDate: '2025-01-18',
    lastContributionDate: '2025-01-12',
    deadline: '2025-06-12',
  },
  {
    id: 'goal_009',
    userId: 'user_009',
    title: 'Wholesale Inventory Buffer',
    category: 'Working Capital',
    targetAmount: 4500,
    currentAmount: 1100,
    status: 'Dormant',
    nextContributionDate: null,
    lastContributionDate: '2024-11-04',
    deadline: '2025-08-01',
  },
  {
    id: 'goal_010',
    userId: 'user_010',
    title: 'Logistics Fleet Upgrade',
    category: 'Logistics',
    targetAmount: 12000,
    currentAmount: 6200,
    status: 'Active',
    nextContributionDate: '2025-01-25',
    lastContributionDate: '2025-01-12',
    deadline: '2025-12-15',
  },
  {
    id: 'goal_011',
    userId: 'user_011',
    title: 'Shop Refresh',
    category: 'Business Growth',
    targetAmount: 1800,
    currentAmount: 1800,
    status: 'Completed',
    nextContributionDate: null,
    lastContributionDate: '2024-12-22',
    deadline: '2024-12-22',
  },
  {
    id: 'goal_012',
    userId: 'user_013',
    title: 'University Tuition',
    category: 'Education',
    targetAmount: 9000,
    currentAmount: 3600,
    status: 'Active',
    nextContributionDate: '2025-01-23',
    lastContributionDate: '2025-01-14',
    deadline: '2025-09-01',
  },
  {
    id: 'goal_013',
    userId: 'user_014',
    title: 'Product Launch Campaign',
    category: 'Marketing',
    targetAmount: 5000,
    currentAmount: 2750,
    status: 'Active',
    nextContributionDate: '2025-01-20',
    lastContributionDate: '2025-01-11',
    deadline: '2025-05-20',
  },
  {
    id: 'goal_014',
    userId: 'user_015',
    title: 'New Baby Fund',
    category: 'Family',
    targetAmount: 4000,
    currentAmount: 1500,
    status: 'Active',
    nextContributionDate: '2025-01-19',
    lastContributionDate: '2025-01-12',
    deadline: '2025-09-30',
  },
  {
    id: 'goal_015',
    userId: 'user_016',
    title: 'Drip Irrigation Upgrade',
    category: 'Agriculture',
    targetAmount: 3200,
    currentAmount: 950,
    status: 'Dormant',
    nextContributionDate: null,
    lastContributionDate: '2024-10-18',
    deadline: '2025-08-18',
  },
];

export const mockMemberDocuments = [
  {
    userId: 'user_001',
    reviewer: 'Ama Owusu',
    updatedAt: '2024-12-18',
    pendingAction: null,
    documents: [
      { id: 'doc-001', type: 'Ghana Card', status: 'Verified', reference: 'GC-447812', uploadedAt: '2024-12-18' },
      { id: 'doc-002', type: 'Utility Bill', status: 'Verified', reference: 'UB-118221', uploadedAt: '2024-12-12' },
    ],
  },
  {
    userId: 'user_002',
    reviewer: 'Compliance Queue',
    updatedAt: '2025-01-12',
    pendingAction: 'Selfie match required',
    documents: [
      { id: 'doc-004', type: 'Ghana Card', status: 'Pending Review', reference: 'GC-774112', uploadedAt: '2025-01-11' },
      { id: 'doc-005', type: 'Utility Bill', status: 'Pending Review', reference: 'UB-774118', uploadedAt: '2025-01-10' },
    ],
  },
  {
    userId: 'user_003',
    reviewer: 'Ekow Nartey',
    updatedAt: '2024-12-30',
    pendingAction: null,
    documents: [
      { id: 'doc-006', type: 'Ghana Card', status: 'Verified', reference: 'GC-551204', uploadedAt: '2024-12-29' },
      { id: 'doc-007', type: 'Bank Statement', status: 'Verified', reference: 'BS-771203', uploadedAt: '2024-12-28' },
    ],
  },
  {
    userId: 'user_004',
    reviewer: 'Akosua Boateng',
    updatedAt: '2025-01-10',
    pendingAction: null,
    documents: [
      { id: 'doc-008', type: 'Ghana Card', status: 'Verified', reference: 'GC-551122', uploadedAt: '2025-01-09' },
      { id: 'doc-009', type: 'Business Permit', status: 'Verified', reference: 'BP-440912', uploadedAt: '2025-01-08' },
    ],
  },
  {
    userId: 'user_005',
    reviewer: 'Compliance Escalations',
    updatedAt: '2025-01-10',
    pendingAction: 'Refresh bank statement',
    documents: [
      { id: 'doc-010', type: 'Ghana Card', status: 'Verified', reference: 'GC-880552', uploadedAt: '2024-12-18' },
      { id: 'doc-011', type: 'Bank Statement', status: 'Expired', reference: 'BS-110400', uploadedAt: '2024-09-30' },
    ],
  },
  {
    userId: 'user_006',
    reviewer: 'Compliance Queue',
    updatedAt: '2025-01-13',
    pendingAction: 'Confirm selfie upload',
    documents: [
      { id: 'doc-012', type: 'Ghana Card', status: 'Pending Review', reference: 'GC-998120', uploadedAt: '2025-01-13' },
      { id: 'doc-013', type: 'Utility Bill', status: 'Pending Review', reference: 'UB-998121', uploadedAt: '2025-01-11' },
    ],
  },
  {
    userId: 'user_007',
    reviewer: 'Ekow Nartey',
    updatedAt: '2024-12-05',
    pendingAction: null,
    documents: [
      { id: 'doc-014', type: 'Ghana Card', status: 'Verified', reference: 'GC-660903', uploadedAt: '2024-12-04' },
      { id: 'doc-015', type: 'Business Permit', status: 'Verified', reference: 'BP-660904', uploadedAt: '2024-12-04' },
    ],
  },
  {
    userId: 'user_008',
    reviewer: 'Ama Owusu',
    updatedAt: '2025-01-07',
    pendingAction: null,
    documents: [
      { id: 'doc-016', type: 'Ghana Card', status: 'Verified', reference: 'GC-214774', uploadedAt: '2025-01-06' },
      { id: 'doc-017', type: 'Utility Bill', status: 'Verified', reference: 'UB-214775', uploadedAt: '2025-01-06' },
    ],
  },
  {
    userId: 'user_009',
    reviewer: 'Compliance Queue',
    updatedAt: '2025-01-09',
    pendingAction: 'Proof of address outstanding',
    documents: [
      { id: 'doc-018', type: 'Ghana Card', status: 'Pending Review', reference: 'GC-502110', uploadedAt: '2025-01-08' },
      { id: 'doc-019', type: 'Utility Bill', status: 'Missing', reference: 'UB-502111', uploadedAt: null },
    ],
  },
  {
    userId: 'user_010',
    reviewer: 'Akosua Boateng',
    updatedAt: '2025-01-03',
    pendingAction: null,
    documents: [
      { id: 'doc-020', type: 'Ghana Card', status: 'Verified', reference: 'GC-101338', uploadedAt: '2025-01-02' },
      { id: 'doc-021', type: 'Business Permit', status: 'Verified', reference: 'BP-101339', uploadedAt: '2025-01-02' },
    ],
  },
  {
    userId: 'user_011',
    reviewer: 'Ama Owusu',
    updatedAt: '2024-12-20',
    pendingAction: null,
    documents: [
      { id: 'doc-022', type: 'Ghana Card', status: 'Verified', reference: 'GC-442110', uploadedAt: '2024-12-19' },
      { id: 'doc-023', type: 'Utility Bill', status: 'Verified', reference: 'UB-442111', uploadedAt: '2024-12-19' },
    ],
  },
  {
    userId: 'user_012',
    reviewer: 'Compliance Escalations',
    updatedAt: '2024-03-29',
    pendingAction: 'Request clearer Ghana Card scan',
    documents: [
      { id: 'doc-024', type: 'Ghana Card', status: 'Rejected', reference: 'GC-440998', uploadedAt: '2024-03-28' },
      { id: 'doc-025', type: 'Proof of Address', status: 'Missing', reference: 'PA-440999', uploadedAt: null },
    ],
  },
  {
    userId: 'user_013',
    reviewer: 'Ekow Nartey',
    updatedAt: '2025-01-11',
    pendingAction: null,
    documents: [
      { id: 'doc-026', type: 'Ghana Card', status: 'Verified', reference: 'GC-778120', uploadedAt: '2025-01-10' },
      { id: 'doc-027', type: 'Utility Bill', status: 'Verified', reference: 'UB-778121', uploadedAt: '2025-01-09' },
    ],
  },
  {
    userId: 'user_014',
    reviewer: 'Ama Owusu',
    updatedAt: '2025-01-08',
    pendingAction: null,
    documents: [
      { id: 'doc-028', type: 'Ghana Card', status: 'Verified', reference: 'GC-908224', uploadedAt: '2025-01-07' },
      { id: 'doc-029', type: 'Business Permit', status: 'Verified', reference: 'BP-908225', uploadedAt: '2025-01-07' },
    ],
  },
  {
    userId: 'user_015',
    reviewer: 'Compliance Queue',
    updatedAt: '2025-01-12',
    pendingAction: 'Confirm newborn certificate upload',
    documents: [
      { id: 'doc-030', type: 'Ghana Card', status: 'Pending Review', reference: 'GC-667335', uploadedAt: '2025-01-12' },
      { id: 'doc-031', type: 'Utility Bill', status: 'Pending Review', reference: 'UB-667336', uploadedAt: '2025-01-11' },
    ],
  },
  {
    userId: 'user_016',
    reviewer: 'Akosua Boateng',
    updatedAt: '2025-01-05',
    pendingAction: null,
    documents: [
      { id: 'doc-032', type: 'Ghana Card', status: 'Verified', reference: 'GC-311770', uploadedAt: '2025-01-04' },
      { id: 'doc-033', type: 'Farm Registration', status: 'Verified', reference: 'FR-311771', uploadedAt: '2025-01-04' },
    ],
  },
];

export const dashboardKpiPreviousWeek = {
  activeMembers: 14,
  totalSavings: 24820.5,
  pendingPayouts: 3,
  openDisputes: 5,
};

export type CashflowChecklistStatus = 'Complete' | 'Pending' | 'Flagged';

export type CashflowQueueItem = {
  id: string;
  reference: string;
  member: string;
  memberId: string;
  group?: string;
  amount: number;
  channel: string;
  status: string;
  risk: 'Low' | 'Medium' | 'High';
  type: 'Deposit' | 'Withdrawal';
  submittedAt: string;
  updatedAt: string;
  analyst: string;
  notes: string;
  compliance: {
    label: string;
    status: CashflowChecklistStatus;
    note?: string;
  }[];
  timeline: {
    label: string;
    timestamp: string;
    note?: string;
  }[];
  fees: {
    label: string;
    amount: number;
    note?: string;
  }[];
};

export const mockCashflowQueues: Record<'deposits' | 'withdrawals', CashflowQueueItem[]> = {
  deposits: [
    {
      id: 'CF-DEP-001',
      reference: 'DEP-882154',
      member: 'Kwame Mensah',
      memberId: 'user_001',
      group: 'Unity Savers Group',
      amount: 500.5,
      channel: 'MTN MoMo',
      status: 'In Review',
      risk: 'Medium',
      type: 'Deposit',
      submittedAt: '2025-01-15T09:45:00Z',
      updatedAt: '2025-01-15T10:05:00Z',
      analyst: 'Ama Larbi',
      notes: 'Awaiting MTN confirmation pin before releasing funds to wallet.',
      compliance: [
        { label: 'Member KYC completed', status: 'Complete' },
        { label: 'MoMo confirmation received', status: 'Pending', note: 'Subscriber must confirm in-app prompt.' },
        { label: 'Deposit amount within policy', status: 'Complete' },
        { label: 'AML screening', status: 'Complete' },
      ],
      timeline: [
        { label: 'Submitted', timestamp: '2025-01-15T09:45:00Z', note: 'Member initiated via mobile app.' },
        { label: 'MoMo prompt sent', timestamp: '2025-01-15T09:47:00Z' },
        { label: 'Compliance review started', timestamp: '2025-01-15T09:55:00Z', note: 'Assigned to Ama Larbi.' },
      ],
      fees: [
        { label: 'Platform fee', amount: 3.5 },
        { label: 'MoMo processing', amount: 1.2 },
      ],
    },
    {
      id: 'CF-DEP-002',
      reference: 'DEP-331205',
      member: 'Akua Frimpong',
      memberId: 'user_006',
      group: 'Unity Savers Group',
      amount: 210.0,
      channel: 'MTN MoMo',
      status: 'Pending',
      risk: 'Low',
      type: 'Deposit',
      submittedAt: '2025-01-14T15:58:00Z',
      updatedAt: '2025-01-14T16:02:00Z',
      analyst: 'Kojo Nartey',
      notes: 'Auto-clears after mobile confirmation expires in 5 minutes.',
      compliance: [
        { label: 'Member KYC completed', status: 'Complete' },
        { label: 'MoMo confirmation received', status: 'Pending' },
        { label: 'Fraud rules triggered', status: 'Complete' },
        { label: 'Amount threshold (< GH₵ 1,000)', status: 'Complete' },
      ],
      timeline: [
        { label: 'Submitted', timestamp: '2025-01-14T15:58:00Z' },
        { label: 'MoMo prompt sent', timestamp: '2025-01-14T15:58:30Z' },
      ],
      fees: [
        { label: 'Platform fee', amount: 1.05 },
        { label: 'MoMo processing', amount: 0.7 },
      ],
    },
    {
      id: 'CF-DEP-003',
      reference: 'DEP-441205',
      member: 'Yaw Boateng',
      memberId: 'user_005',
      group: 'Unity Savers Group',
      amount: 180.0,
      channel: 'AirtelTigo Money',
      status: 'Flagged',
      risk: 'High',
      type: 'Deposit',
      submittedAt: '2025-01-14T16:40:00Z',
      updatedAt: '2025-01-14T17:10:00Z',
      analyst: 'Kukua Owusu',
      notes: 'KYC mismatch detected. Awaiting updated Ghana Card upload from member.',
      compliance: [
        { label: 'Member KYC completed', status: 'Flagged', note: 'ID expired on 2024-12-20.' },
        { label: 'MoMo confirmation received', status: 'Complete' },
        { label: 'Manual escalation review', status: 'Pending' },
        { label: 'AML screening', status: 'Complete' },
      ],
      timeline: [
        { label: 'Submitted', timestamp: '2025-01-14T16:40:00Z' },
        { label: 'Compliance flagged', timestamp: '2025-01-14T16:45:00Z', note: 'Auto rule: expired ID.' },
        { label: 'Analyst assigned', timestamp: '2025-01-14T16:50:00Z', note: 'Assigned to Kukua Owusu.' },
      ],
      fees: [
        { label: 'Platform fee', amount: 0 },
        { label: 'MoMo processing', amount: 0 },
      ],
    },
    {
      id: 'CF-DEP-004',
      reference: 'DEP-771203',
      member: 'Ama Darko',
      memberId: 'user_002',
      group: 'Women Empowerment Circle',
      amount: 320.0,
      channel: 'Vodafone Cash',
      status: 'Cleared',
      risk: 'Low',
      type: 'Deposit',
      submittedAt: '2025-01-15T09:10:00Z',
      updatedAt: '2025-01-15T09:18:00Z',
      analyst: 'Ama Larbi',
      notes: 'Released to wallet. Auto receipt emailed to member.',
      compliance: [
        { label: 'Member KYC completed', status: 'Complete' },
        { label: 'MoMo confirmation received', status: 'Complete' },
        { label: 'Fraud rules triggered', status: 'Complete' },
        { label: 'AML screening', status: 'Complete' },
      ],
      timeline: [
        { label: 'Submitted', timestamp: '2025-01-15T09:10:00Z' },
        { label: 'MoMo confirmation', timestamp: '2025-01-15T09:11:00Z' },
        { label: 'Funds released', timestamp: '2025-01-15T09:18:00Z' },
      ],
      fees: [
        { label: 'Platform fee', amount: 2.24 },
        { label: 'Vodafone Cash processing', amount: 0.96 },
      ],
    },
    {
      id: 'CF-DEP-005',
      reference: 'DEP-221205',
      member: 'Efua Adjei',
      memberId: 'user_007',
      group: 'Accra Market Vendors',
      amount: 720.0,
      channel: 'Bank Transfer',
      status: 'Failed',
      risk: 'Medium',
      type: 'Deposit',
      submittedAt: '2025-01-14T12:26:00Z',
      updatedAt: '2025-01-14T12:52:00Z',
      analyst: 'Kojo Nartey',
      notes: 'Bank rejected transfer due to incorrect reference. Operator notified member to retry.',
      compliance: [
        { label: 'Member KYC completed', status: 'Complete' },
        { label: 'Bank transfer verified', status: 'Flagged', note: 'Reference mismatch' },
        { label: 'Manual escalation review', status: 'Complete' },
        { label: 'AML screening', status: 'Complete' },
      ],
      timeline: [
        { label: 'Submitted', timestamp: '2025-01-14T12:26:00Z' },
        { label: 'Bank validation failed', timestamp: '2025-01-14T12:36:00Z' },
        { label: 'Member notified', timestamp: '2025-01-14T12:52:00Z' },
      ],
      fees: [
        { label: 'Platform fee', amount: 0 },
        { label: 'Bank processing', amount: 0 },
      ],
    },
  ],
  withdrawals: [
    {
      id: 'CF-WDR-001',
      reference: 'WDR-552208',
      member: 'Yaw Boateng',
      memberId: 'user_005',
      group: 'Unity Savers Group',
      amount: 450.0,
      channel: 'MTN MoMo',
      status: 'Awaiting Approval',
      risk: 'Medium',
      type: 'Withdrawal',
      submittedAt: '2025-01-15T08:20:00Z',
      updatedAt: '2025-01-15T09:00:00Z',
      analyst: 'Nana Darkwah',
      notes: 'Pending supervisor sign-off after confirming contribution history.',
      compliance: [
        { label: 'Savings goal balance verified', status: 'Complete' },
        { label: 'Contribution streak intact', status: 'Complete' },
        { label: 'Withdrawal declaration signed', status: 'Pending' },
        { label: 'AML screening', status: 'Complete' },
      ],
      timeline: [
        { label: 'Submitted', timestamp: '2025-01-15T08:20:00Z' },
        { label: 'Analyst review started', timestamp: '2025-01-15T08:32:00Z' },
        { label: 'Supervisor approval requested', timestamp: '2025-01-15T08:58:00Z' },
      ],
      fees: [
        { label: 'Platform fee', amount: 2.7 },
        { label: 'MoMo payout fee', amount: 1.5 },
      ],
    },
    {
      id: 'CF-WDR-002',
      reference: 'WDR-552198',
      member: 'Ama Darko',
      memberId: 'user_002',
      group: 'Women Empowerment Circle',
      amount: 600.0,
      channel: 'Bank Transfer',
      status: 'On Hold',
      risk: 'High',
      type: 'Withdrawal',
      submittedAt: '2025-01-14T19:10:00Z',
      updatedAt: '2025-01-15T07:45:00Z',
      analyst: 'Efua Hammond',
      notes: 'Awaiting verification of new bank account provided during payout request.',
      compliance: [
        { label: 'Savings goal balance verified', status: 'Complete' },
        { label: 'Contribution streak intact', status: 'Complete' },
        { label: 'Bank account ownership proof', status: 'Pending', note: 'Member uploaded utility bill for review.' },
        { label: 'AML screening', status: 'Flagged', note: 'Name mismatch with bank.' },
      ],
      timeline: [
        { label: 'Submitted', timestamp: '2025-01-14T19:10:00Z' },
        { label: 'Bank verification requested', timestamp: '2025-01-14T19:25:00Z' },
        { label: 'Member uploaded document', timestamp: '2025-01-15T07:32:00Z' },
      ],
      fees: [
        { label: 'Platform fee', amount: 4.2 },
        { label: 'Bank transfer fee', amount: 2.0 },
      ],
    },
    {
      id: 'CF-WDR-003',
      reference: 'WDR-662145',
      member: 'Abena Osei',
      memberId: 'user_004',
      group: 'Unity Savers Group',
      amount: 350.0,
      channel: 'MTN MoMo',
      status: 'Released',
      risk: 'Low',
      type: 'Withdrawal',
      submittedAt: '2025-01-13T17:40:00Z',
      updatedAt: '2025-01-13T18:05:00Z',
      analyst: 'Nana Darkwah',
      notes: 'Completed without holds. Receipt stored in documents tab.',
      compliance: [
        { label: 'Savings goal balance verified', status: 'Complete' },
        { label: 'Contribution streak intact', status: 'Complete' },
        { label: 'Withdrawal declaration signed', status: 'Complete' },
        { label: 'AML screening', status: 'Complete' },
      ],
      timeline: [
        { label: 'Submitted', timestamp: '2025-01-13T17:40:00Z' },
        { label: 'Compliance review started', timestamp: '2025-01-13T17:44:00Z' },
        { label: 'Funds released', timestamp: '2025-01-13T18:05:00Z' },
      ],
      fees: [
        { label: 'Platform fee', amount: 2.45 },
        { label: 'MoMo payout fee', amount: 1.3 },
      ],
    },
    {
      id: 'CF-WDR-004',
      reference: 'WDR-772122',
      member: 'Kwesi Owusu',
      memberId: 'user_009',
      group: 'Traders Alliance',
      amount: 900.0,
      channel: 'Bank Transfer',
      status: 'Failed',
      risk: 'Medium',
      type: 'Withdrawal',
      submittedAt: '2025-01-12T11:15:00Z',
      updatedAt: '2025-01-12T13:20:00Z',
      analyst: 'Efua Hammond',
      notes: 'Bank rejected payout due to insufficient float. Queue auto-retries after treasury top-up.',
      compliance: [
        { label: 'Savings goal balance verified', status: 'Complete' },
        { label: 'Contribution streak intact', status: 'Complete' },
        { label: 'Treasury float available', status: 'Flagged', note: 'Insufficient float at 12:45.' },
        { label: 'AML screening', status: 'Complete' },
      ],
      timeline: [
        { label: 'Submitted', timestamp: '2025-01-12T11:15:00Z' },
        { label: 'Treasury verification', timestamp: '2025-01-12T11:45:00Z' },
        { label: 'Bank payout failed', timestamp: '2025-01-12T13:20:00Z' },
      ],
      fees: [
        { label: 'Platform fee', amount: 0 },
        { label: 'Bank transfer fee', amount: 0 },
      ],
    },
  ],
};

export const mockDisputes = [
  {
    id: 'DIS-1001',
    title: 'Missing Contribution Payment',
    user: 'Abena Osei',
    group: 'Unity Savers Group',
    status: 'Open',
    date: '2025-01-08',
    priority: 'High',
    severity: 'Critical',
    category: 'Wallet & Cashflow',
    channel: 'Mobile App',
    assignedTo: 'Maame Esi',
    openedAt: '2025-01-08T08:45:00Z',
    lastUpdated: '2025-01-09T10:10:00Z',
    slaDue: '2025-01-10T16:00:00Z',
    slaStatus: 'At Risk',
    relatedFaqId: 'faq-contribution-missing-payment',
    conversation: [
      {
        id: 'DIS-1001-msg-1',
        author: 'Abena Osei',
        role: 'Member',
        channel: 'In-app',
        message:
          'I contributed GH₵ 250 yesterday via MTN MoMo but the amount is still missing from my susu balance.',
        timestamp: '2025-01-08T08:45:00Z',
      },
      {
        id: 'DIS-1001-msg-2',
        author: 'Maame Esi',
        role: 'Support',
        channel: 'In-app Reply',
        message:
          'Thanks Abena — we are reconciling with the MoMo processor. Could you upload your receipt while we review the ledger?',
        timestamp: '2025-01-08T09:10:00Z',
      },
      {
        id: 'DIS-1001-msg-3',
        author: 'Abena Osei',
        role: 'Member',
        channel: 'In-app',
        message: 'Receipt attached. Please let me know if you need anything else.',
        timestamp: '2025-01-08T09:25:00Z',
      },
    ],
    attachments: [
      {
        id: 'DIS-1001-att-1',
        fileName: 'mtn-receipt-abena.pdf',
        type: 'application/pdf',
        size: '340 KB',
      },
      {
        id: 'DIS-1001-att-2',
        fileName: 'ledger-diff.png',
        type: 'image/png',
        size: '820 KB',
      },
    ],
  },
  {
    id: 'DIS-1002',
    title: 'Delayed Payout Issue',
    user: 'Ama Darko',
    group: 'Women Empowerment Circle',
    status: 'In Review',
    date: '2025-01-07',
    priority: 'Medium',
    severity: 'High',
    category: 'Wallet & Cashflow',
    channel: 'USSD',
    assignedTo: 'Yaw Bediako',
    openedAt: '2025-01-07T14:05:00Z',
    lastUpdated: '2025-01-09T12:20:00Z',
    slaDue: '2025-01-10T11:30:00Z',
    slaStatus: 'On Track',
    relatedFaqId: 'faq-payout-delay',
    conversation: [
      {
        id: 'DIS-1002-msg-1',
        author: 'Ama Darko',
        role: 'Member',
        channel: 'Phone',
        message: 'My rotation payout is 3 hours late and still pending in the app.',
        timestamp: '2025-01-07T14:05:00Z',
      },
      {
        id: 'DIS-1002-msg-2',
        author: 'Yaw Bediako',
        role: 'Support',
        channel: 'Phone Log',
        message: 'Explained payout is pending compliance check and will clear once mobile money reconciles.',
        timestamp: '2025-01-07T15:00:00Z',
      },
      {
        id: 'DIS-1002-msg-3',
        author: 'Compliance Bot',
        role: 'Automation',
        channel: 'System Note',
        message: 'AML review cleared — releasing payout once treasury window opens at 16:00 GMT.',
        timestamp: '2025-01-09T10:45:00Z',
      },
    ],
    attachments: [
      {
        id: 'DIS-1002-att-1',
        fileName: 'payout-audit-log.csv',
        type: 'text/csv',
        size: '28 KB',
      },
    ],
  },
  {
    id: 'DIS-1003',
    title: 'Incorrect Amount Deducted',
    user: 'Kwabena Ofori',
    group: 'Ashesi Alumni Builders',
    status: 'Resolved',
    date: '2025-01-05',
    priority: 'Low',
    severity: 'Medium',
    category: 'Account & KYC',
    channel: 'Email',
    assignedTo: 'Ama Tetteh',
    openedAt: '2025-01-05T07:20:00Z',
    lastUpdated: '2025-01-06T16:45:00Z',
    slaDue: '2025-01-08T09:00:00Z',
    slaStatus: 'Breached',
    relatedFaqId: 'faq-account-adjustment',
    conversation: [
      {
        id: 'DIS-1003-msg-1',
        author: 'Kwabena Ofori',
        role: 'Member',
        channel: 'Email',
        message: 'My wallet was debited GH₵ 120 twice when approving my KYC update.',
        timestamp: '2025-01-05T07:20:00Z',
      },
      {
        id: 'DIS-1003-msg-2',
        author: 'Ama Tetteh',
        role: 'Support',
        channel: 'Email Reply',
        message: 'Confirmed duplicate deduction, issued manual credit and notified treasury to reconcile.',
        timestamp: '2025-01-05T11:40:00Z',
      },
      {
        id: 'DIS-1003-msg-3',
        author: 'Ama Tetteh',
        role: 'Support',
        channel: 'System Note',
        message: 'Case resolved with manual adjustment. Awaiting member confirmation.',
        timestamp: '2025-01-06T16:45:00Z',
      },
    ],
    attachments: [
      {
        id: 'DIS-1003-att-1',
        fileName: 'duplicate-charge-refund.pdf',
        type: 'application/pdf',
        size: '215 KB',
      },
    ],
  },
  {
    id: 'DIS-1004',
    title: 'Withdrawal Compliance Hold',
    user: 'Yaw Boateng',
    group: 'Unity Savers Group',
    status: 'Open',
    date: '2025-01-09',
    priority: 'High',
    severity: 'High',
    category: 'Compliance & Risk',
    channel: 'Mobile App',
    assignedTo: 'Compliance Desk',
    openedAt: '2025-01-09T06:55:00Z',
    lastUpdated: '2025-01-09T11:20:00Z',
    slaDue: '2025-01-10T08:00:00Z',
    slaStatus: 'At Risk',
    relatedFaqId: 'faq-withdrawal-compliance',
    conversation: [
      {
        id: 'DIS-1004-msg-1',
        author: 'System Alert',
        role: 'Automation',
        channel: 'System',
        message: 'Withdrawal flagged for manual review after three failed KYC checks.',
        timestamp: '2025-01-09T06:55:00Z',
      },
      {
        id: 'DIS-1004-msg-2',
        author: 'Yaw Boateng',
        role: 'Member',
        channel: 'In-app',
        message: 'I submitted my ID yesterday. Any update on the withdrawal?',
        timestamp: '2025-01-09T08:15:00Z',
      },
      {
        id: 'DIS-1004-msg-3',
        author: 'Compliance Desk',
        role: 'Support',
        channel: 'In-app Reply',
        message: 'Reviewing enhanced due diligence responses. Will confirm release ETA shortly.',
        timestamp: '2025-01-09T11:20:00Z',
      },
    ],
    attachments: [
      {
        id: 'DIS-1004-att-1',
        fileName: 'enhanced-kyc-checklist.xlsx',
        type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        size: '64 KB',
      },
    ],
  },
  {
    id: 'DIS-1005',
    title: 'Invite Reminder Escalation',
    user: 'Akua Frimpong',
    group: 'Women Empowerment Circle',
    status: 'In Review',
    date: '2025-01-06',
    priority: 'Medium',
    severity: 'Medium',
    category: 'Susu Groups',
    channel: 'Mobile App',
    assignedTo: 'Group Success Pod',
    openedAt: '2025-01-06T12:10:00Z',
    lastUpdated: '2025-01-08T09:35:00Z',
    slaDue: '2025-01-09T15:30:00Z',
    slaStatus: 'On Track',
    relatedFaqId: 'faq-group-invite',
    conversation: [
      {
        id: 'DIS-1005-msg-1',
        author: 'Akua Frimpong',
        role: 'Member',
        channel: 'In-app',
        message: 'Two invitees still haven\'t accepted after 3 reminders. What else can I do?',
        timestamp: '2025-01-06T12:10:00Z',
      },
      {
        id: 'DIS-1005-msg-2',
        author: 'Group Success Pod',
        role: 'Support',
        channel: 'In-app Reply',
        message: 'We\'re preparing manual SMS outreach and will update within the next cycle.',
        timestamp: '2025-01-07T09:05:00Z',
      },
    ],
    attachments: [
      {
        id: 'DIS-1005-att-1',
        fileName: 'invite-reminder-script.txt',
        type: 'text/plain',
        size: '4 KB',
      },
    ],
  },
];

export const publicGroupJoinFlow: PublicGroupJoinFlow = {
  expectation: 'Smart matches • Live vetting • Trust signals',
  steps: [
    {
      id: 'discover',
      badge: 'Step 1',
      title: 'Discover curated groups',
      description: 'Filter public cohorts by contribution size, cycle length, and focus area to find the right fit.',
      helper: 'Verified badges spotlight trusted admins, repayment history, and community ratings.',
      icon: Search,
    },
    {
      id: 'apply',
      badge: 'Step 2',
      title: 'Submit smart application',
      description: 'Review the group rules, refresh KYC, and share a purpose statement by voice or text.',
      helper: 'Suggested references from existing members boost acceptance odds automatically.',
      icon: ClipboardCheck,
    },
    {
      id: 'approve',
      badge: 'Step 3',
      title: 'Get approved & onboarded',
      description: 'Approved members instantly see payout order, contribution schedule, and start date.',
      helper: 'Welcome checklist nudges auto-contributions and accountability partner invites.',
      icon: Sparkles,
    },
  ],
  highlights: [
    'Group health scores refresh in real time using repayment data and attendance logs.',
    'Digital agreements capture NDA and constitution signatures securely.',
    'Members stay engaged with group chat, voice drops, and scheduled reminders.',
  ],
};

export const mockSupportArticles = [
  {
    id: 'faq-contribution-missing-payment',
    category: 'Wallet & Cashflow',
    title: 'Reconcile a missing contribution payment',
    summary:
      'Checklist for verifying MoMo receipts, wallet ledgers, and rotation schedules when a contribution fails to post.',
    link: '/support/wallet/missing-contribution',
    tags: ['MoMo', 'Ledger Review', 'Receipts'],
  },
  {
    id: 'faq-payout-delay',
    category: 'Wallet & Cashflow',
    title: 'Resolve delayed susu payouts',
    summary:
      'Troubleshooting guide covering treasury windows, compliance gates, and notifying members during payout delays.',
    link: '/support/wallet/payout-delay',
    tags: ['Payout', 'Compliance', 'Treasury'],
  },
  {
    id: 'faq-account-adjustment',
    category: 'Account & KYC',
    title: 'Undo duplicate wallet deductions',
    summary:
      'Steps to issue manual credits, annotate accounts, and confirm with members when double charges occur.',
    link: '/support/account/duplicate-deductions',
    tags: ['Adjustments', 'Wallet'],
  },
  {
    id: 'faq-withdrawal-compliance',
    category: 'Compliance & Risk',
    title: 'Clear withdrawals stuck in compliance review',
    summary:
      'Enhanced due diligence workflow for high-risk withdrawals, including ID checks and escalation paths.',
    link: '/support/compliance/withdrawal-review',
    tags: ['EDD', 'Risk Flags', 'KYC'],
  },
  {
    id: 'faq-group-invite',
    category: 'Susu Groups',
    title: 'Improve invite acceptance for susu groups',
    summary:
      'Outreach templates, reminder cadence, and manual override options for stalled group invitations.',
    link: '/support/groups/invite-acceptance',
    tags: ['Invites', 'Engagement', 'Reminders'],
  },
  {
    id: 'faq-notifications-escalation',
    category: 'Notifications & Alerts',
    title: 'Configure escalation alerts for disputes',
    summary:
      'Map severity tiers to the correct notification channels and ensure escalations reach on-call owners.',
    link: '/support/notifications/escalations',
    tags: ['Alerts', 'Routing'],
  },
];

export const mockNotifications = [
  { id: 1, type: 'alert', message: 'Withdrawal hold: Yaw Boateng requires compliance review', time: '3 mins ago', read: false },
  { id: 2, type: 'success', message: 'Unity Savers Group cycle payout of GH₵ 1,000 completed', time: '25 mins ago', read: false },
  { id: 3, type: 'warning', message: 'Pending deposit confirmation for Akua Frimpong', time: '1 hour ago', read: false },
  { id: 4, type: 'info', message: '13 active members reached 70% savings milestones this week', time: '4 hours ago', read: true },
  { id: 5, type: 'success', message: 'New public group Accra Market Vendors added 5 members', time: 'Yesterday', read: true },
  { id: 6, type: 'info', message: 'Reminder: Send invites follow-up for Women Empowerment Circle', time: '2 days ago', read: true },
];

// Analytics data for charts
export const monthlyRevenueData = [
  { month: 'Aug', revenue: 41200 },
  { month: 'Sep', revenue: 43850 },
  { month: 'Oct', revenue: 46540 },
  { month: 'Nov', revenue: 49820 },
  { month: 'Dec', revenue: 52310 },
  { month: 'Jan', revenue: 54760 },
];

export const groupGrowthData = [
  { month: 'Aug', groups: 48 },
  { month: 'Sep', groups: 55 },
  { month: 'Oct', groups: 62 },
  { month: 'Nov', groups: 70 },
  { month: 'Dec', groups: 78 },
  { month: 'Jan', groups: 84 },
];
